development:
  adapter: mysql2
  username: root
  password: 
  database: chatlogger_dev
  host: localhost
production:
  adapter: mysql2
  username: root
  password:
  database: chatlogger_prod
  host: localhost
test:
  adapter: mysql2
  username: root
  password:
  database: chatlogger_test
  host: localhost
staging:
  adapter: mysql2
  username: root
  password:
  database: chatlogger_stage
  host: localhost
