common: &common
  adapter: postgresql
  username: matheus
  password: # from psql setup, see Postgresql

development:
  <<: *common
  database: chatlogger_development

test:
  <<: *common
  database: chatlogger_test

production:
  <<: *common
  database: chatlogger_production
